### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by SVNTY** [endiliey/rengorum#7]
```
(venv) MacBook-Air:backend admin$ sudo -H pip install -r requirements.txt
Requirement already satisfied: dj-database-url==0.5.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.5.0)
Requirement already satisfied: Django==2.0.12 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: django-cors-headers==2.2.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (2.2.0)
Requirement already satisfied: djangorestframework==3.9.1 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (3.9.1)
Collecting Pillow==5.1.0 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/89/b8/2f49bf71cbd0e9485bb36f72d438421b69b7356180695ae10bd4fd3066f5/Pillow-5.1.0.tar.gz (14.3MB)
     |████████████████████████████████| 14.3MB 1.5MB/s
Collecting PyJWT==1.6.1 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/31/8f/19c302aa9a391dd1fbd249362b749021b88d40fb59af0363939a2250afed/PyJWT-1.6.1-py2.py3-none-any.whl
Collecting python-decouple==3.1 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/9b/99/ddfbb6362af4ee239a012716b1371aa6d316ff1b9db705bfb182fbc4780f/python-decouple-3.1.tar.gz
Requirement already satisfied: pytz==2018.3 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2018.3)
Installing collected packages: Pillow, PyJWT, python-decouple
  Running setup.py install for Pillow ... error
    ERROR: Complete output from command /Users/admin/Projects/srv/rengorum/backend/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-install-1sbxc5c5/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-2tvr6ncl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/admin/Projects/srv/rengorum/backend/venv/include/site/python3.7/Pillow:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/TarIO.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/version.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/FontFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/features.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/_util.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/OleFileIO.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/_binary.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/Image.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.macosx-10.9-x86_64-3.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "/private/tmp/pip-install-1sbxc5c5/Pillow/setup.py", line 794, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW), )
      File "/Users/admin/Projects/srv/rengorum/backend/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/admin/Projects/srv/rengorum/backend/venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/private/tmp/pip-install-1sbxc5c5/Pillow/setup.py", line 582, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-1sbxc5c5/Pillow/setup.py", line 806, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html


    ----------------------------------------
ERROR: Command "/Users/admin/Projects/srv/rengorum/backend/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-install-1sbxc5c5/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-2tvr6ncl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/admin/Projects/srv/rengorum/backend/venv/include/site/python3.7/Pillow" failed with error code 1 in /private/tmp/pip-install-1sbxc5c5/Pillow/
```

I know literally nothing about python unfourtnately

**Comment by SVNTY** [comment]
I removed the Pillow line from requirements.txt and install yarn globally with `npm i -g yarn` and it works
